basePath: /
definitions:
  model.Todo:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      status:
        type: string
      title:
        type: string
      updated_at:
        type: string
    required:
    - title
    type: object
host: localhost:9000
info:
  contact: {}
  description: This is a kanbanAPI
  license: {}
  title: Swagger Example API
  version: "1.0"
paths:
  /todo/{status}:
    get:
      description: get string by status
      parameters:
      - description: input status
        in: path
        name: status
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Todo'
            type: object
      summary: Show a todo by staus
swagger: "2.0"
